### ISSUE TITLE
Server Side - Mysterious Crash with Exception in server tick loop

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [P3rf3ctXZer0/Zer0Necrosis-Project-Workbench#2]
Crashlog
https://gist.github.com/P3rf3ctXZer0/2b521f988d9f2a1f5fc7927ca286dc4d

**Comment by P3rf3ctXZer0** [comment]
@Hugman76 , @DoctorFTB

**Comment by DoctorFTB** [comment]
Helloo..
Can u try downgrade one of mods? 
Can u try with new world? 
Can u try with only one mod?

**Comment by P3rf3ctXZer0** [comment]
I would prefer to not tear my entire pack apart again - I am doing it anyways but it would be nice if you guys could spot a problem before I waste 12 hours.

**Comment by Hugman76** [comment]
Hello.
The version you are using for Mubble is the beta 1.3-pre2. Either do not use betas (and use the stable 1.2.2 instead) or upgrade to beta 1.3-pre3. But as always, betas are not recommended for survival playing. These are **very** instable.

Thanks for the report though, I'll try to see what's wrong with it if it comes from Mubble.

**Comment by SilentChaos512** [comment]
Looks like an entity is being spawned outside the main thread. Best thing to do is make sure you are not spawning entities in, for example, a packet. No way to know which mod is the cause without testing.

**Comment by P3rf3ctXZer0** [comment]
Strange - Any tips for the best way to do this would any Java tools be helpful @SilentChaos512

**Comment by P3rf3ctXZer0** [comment]
New information https://gist.github.com/P3rf3ctXZer0/14afb690229c4964861a6263598dc36f
