### ISSUE TITLE
Flight kick

### ISSUE THREAD

**Issue by FormulaNewts** [P3rf3ctXZer0/Zer0Necrosis-Project-Workbench#22]
I know it's an anti-cheat thing, but every time we jump too high in ultraspace, lag while flying on a Pokemon or lag when we just happen to be in the air we get kicked for flying. It's a constant thing that keeps happening and makes ultraspace annoying to explore. Please enable flight. I know, you want to prevent hackers from being on the server. However, we have Pokemon for flight so even if one does show up and fly, it's really nbd because technically we can all fly at some point.

**Comment by P3rf3ctXZer0** [comment]
I will double check the configs - I don't think I disabled flight.

**Comment by P3rf3ctXZer0** [comment]
after checking it appears flight was disabled i am restarting the server now.
