### ISSUE TITLE
Pheremosa hoard???

### ISSUE THREAD

**Issue by FormulaNewts** [P3rf3ctXZer0/Zer0Necrosis-Project-Workbench#23]
As soon as you step into an Ultra Desert biome in ultraspace, you get just absolutely molested by Pheremosa. I mean, everywhere you look there's like 20 of them. Please adjust the spawn rates. Pheremosa is an invasive species. They're taking hostage of my family. Help. (no but in all seriousness please adjust the spawn rates they're more common than Rattata in terms of spawns at this point)

**Comment by P3rf3ctXZer0** [comment]
I need someone to confirm this is no longer an issue.
