### ISSUE TITLE
Please add Pixelmon Extras

### ISSUE THREAD

**Issue by FormulaNewts** [P3rf3ctXZer0/Zer0Necrosis-Project-Workbench#24]
It's like Bukkit for Pixelmon. Not only does it make life easier for the admins/owners, it makes it easier for players as well. You can read up on the plug-in here:
https://pixelmonmod.com/wiki/index.php?title=Pixelmon_Extras
It's a server side mod, so the players don't necessarily need to download it to play on the server.

**Comment by P3rf3ctXZer0** [comment]
I have discussed this with Erlos - I should have no problems adding it. It is slated for release 2
